
import javax.swing.JOptionPane;
import java.net.*;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sai Shriram
 */
public class Chat_Client_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Chat_Client
     */
    public Chat_Client_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Curr_Log_Title_Label = new javax.swing.JLabel();
        Log_In_As_Label = new javax.swing.JLabel();
        Connect_Btn = new javax.swing.JButton();
        Discon_Btn = new javax.swing.JButton();
        Help_Btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Send_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Conversation_TA = new javax.swing.JTextArea();
        Conv_Label = new javax.swing.JLabel();
        Online_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Online_List = new javax.swing.JList();
        Msg_Label = new javax.swing.JLabel();
        Msg_Field = new javax.swing.JTextField();
        Attach_Btn = new javax.swing.JButton();
        Download_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Curr_Log_Title_Label.setText("Currently Logged In As:");
        getContentPane().add(Curr_Log_Title_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 28));

        Log_In_As_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Log_In_As_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Log_In_As_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, 20));

        Connect_Btn.setText("CONNECT");
        Connect_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Connect_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 61, 97, -1));

        Discon_Btn.setText("DISCONNECT");
        Discon_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discon_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Discon_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 61, -1, -1));

        Help_Btn.setText("HELP");
        Help_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Help_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 61, 97, -1));

        jButton4.setText("ABOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 61, 97, -1));

        Send_Btn.setText("SEND");
        Send_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Send_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, 40));

        Conversation_TA.setColumns(20);
        Conversation_TA.setRows(5);
        jScrollPane1.setViewportView(Conversation_TA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 330, 220));

        Conv_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Conv_Label.setText("CONVERSATION");
        getContentPane().add(Conv_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, 20));

        Online_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Online_Label.setText("CURRENTLY ONLINE");
        getContentPane().add(Online_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 150, -1));

        jScrollPane2.setViewportView(Online_List);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 130, 220));

        Msg_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Msg_Label.setText("YOUR MESSAGE:");
        getContentPane().add(Msg_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 130, 30));

        Msg_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Msg_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Msg_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 340, 40));

        Attach_Btn.setText("Attach");
        Attach_Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Attach_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attach_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Attach_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 179, 30));

        Download_Btn.setText("DOWNLOAD");
        Download_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Download_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Download_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 458, 182, 37));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String username = "Anonymous";
    private static Chat_Client ChatClient;
    File SelectedFile;
    JList list;

    public void connect() {
        try {
            final int port = 1234;
            final String Host = "Shriram";
            Socket sock = new Socket(Host, port);
            System.out.println("You are connected to " + Host);

            ChatClient = new Chat_Client(sock);

            PrintWriter out = new PrintWriter(sock.getOutputStream());
            out.println(username);
            out.flush();

            Thread th = new Thread(ChatClient);
            th.start();

        } catch (Exception ex) {
            System.out.println("Unable to connect to server!!!");
        }

    }

    private void Help_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Help_BtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void Send_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_BtnActionPerformed
        if (!Msg_Field.getText().equals("")) {
            ChatClient.send(Msg_Field.getText());
            Msg_Field.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_Send_BtnActionPerformed

    private void Msg_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Msg_FieldActionPerformed
        Send_Btn.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_Msg_FieldActionPerformed

    private void Discon_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discon_BtnActionPerformed
        try {
            ChatClient.disconnect();        // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Chat_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Discon_BtnActionPerformed

    private void Connect_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_BtnActionPerformed
        
        String temp = JOptionPane.showInputDialog(this, "Enter Username");
        if (!temp.equals("")) {
            username = temp;
            Chat_Server.Users.add(username);
            connect();
            Log_In_As_Label.setText(username);
        } else {
            JOptionPane.showMessageDialog(this, "Enter Valid Username");
            
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Connect_BtnActionPerformed

    private void Attach_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attach_BtnActionPerformed
        try {
            File Selected_File = null;
            InputStream inputstream = null;
            JFileChooser chooser = new JFileChooser();
            int open = chooser.showOpenDialog(this);

            if (open == JFileChooser.APPROVE_OPTION) {
                Selected_File = chooser.getSelectedFile();
                inputstream = new FileInputStream(new File(Selected_File.getAbsolutePath()));
            } else if (open != JFileChooser.APPROVE_OPTION) {
                chooser.setVisible(false);
            }

            if (Selected_File != null) {
                String url = "jdbc:mysql://localhost:3306/connect";
                Connection conn;
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(url, "root", "sairam");
                PreparedStatement pre = conn.prepareStatement("Insert into Files values(?,?,?);");
                pre.setString(1, username);
                pre.setBlob(2, inputstream);
                pre.setString(3, Selected_File.getAbsolutePath());
                int rows = pre.executeUpdate();

                if (rows > 0) {
                    System.out.println("SUCCESS");
                    JOptionPane.showMessageDialog(this, "File Uploade to Server Database");
                    ChatClient.send(username + " Uploaded A File");
                } else {
                    System.out.println("FAIL");
                }
            }
        } catch (ClassNotFoundException | SQLException | FileNotFoundException ex) {
            Logger.getLogger(Chat_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {

        }


    }//GEN-LAST:event_Attach_BtnActionPerformed

    private void Download_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Download_BtnActionPerformed
        String url = "jdbc:mysql://localhost:3306/connect";
        //@SuppressWarnings("UnusedAssignment")
        Connection conn;
        //Statement stmt = null;
        ResultSet rs;
        List_Of_Files lof = new List_Of_Files();
        DefaultListModel listmodel = new DefaultListModel();
        DefaultListModel listmodel2 = new DefaultListModel();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, "root", "sairam");
            PreparedStatement ps = conn.prepareStatement("Select name,path from files;");
            rs = ps.executeQuery();

            while (rs.next()) {
                String name = rs.getString("name");
                String path = rs.getString("path");
                int index = path.lastIndexOf("\\");
                String fin_path = path.substring(index + 1);
                //System.out.println(index);
                listmodel.addElement(name);
                listmodel2.addElement(fin_path);
            }
            lof.jList1.setModel(listmodel);
            lof.jList2.setModel(listmodel2);
            lof.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Exception!!!!");
        }
    }//GEN-LAST:event_Download_BtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Client_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attach_Btn;
    private javax.swing.JButton Connect_Btn;
    private javax.swing.JLabel Conv_Label;
    public static javax.swing.JTextArea Conversation_TA;
    private javax.swing.JLabel Curr_Log_Title_Label;
    private javax.swing.JButton Discon_Btn;
    private javax.swing.JButton Download_Btn;
    private javax.swing.JButton Help_Btn;
    public javax.swing.JLabel Log_In_As_Label;
    public static javax.swing.JTextField Msg_Field;
    private javax.swing.JLabel Msg_Label;
    private javax.swing.JLabel Online_Label;
    public static javax.swing.JList Online_List;
    private javax.swing.JButton Send_Btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
